### ISSUE TITLE
I wish there was a version for Windows as well.

### ISSUE THREAD

**Issue by PlumpMath** [eraserhd/rep#11]
Since the clojure program at the company I work for is a windows version, I wish there was a Windows version as well.
When did the Mac version come out?! It's so good.
I wish I could compile it. Is there no way?

I'm also watching a rust client called ruply.
But now ruply is executed twice. (It seems that it is possible to create a Windows binary called Rust)
Thank you.

**Comment by eraserhd** [comment]
Hi @PlumpMath !

The easy answer (hopefully): You might be able to use Cygwin to compile this on Windows.  I haven't had a Windows machine in a long time, but I hear some people use WSL these days?

The harder (but nicer) answer: The code could be made to compile on Windows without Cygwin using a lot of `#ifdef`s.  I know the `socket()` API has different types on Windows, and requires `#include <winsock.h>` instead of the different POSIX headers.

If you manage to get it working, let me know how!

**Comment by eraserhd** [comment]
I know this has been a while, but @djhaskin987 provided a way to build with Mingw.  I've just updated the README.  I hope this helps.
